### PR TITLE
Export normal and binomial qml forms

### PR DESCRIPTION
**Pull request by Kucharssim**
@JTPetter, this should allow you to reuse the forms in the LearnStats module (https://github.com/jasp-stats/jasp-desktop/blob/stable/Docs/development/jasp-qml-guide.md?rgh-link-date=2022-05-25T13%3A20%3A38Z#custom-imports)

### CODE REVIEW

**Review by JTPetter — APPROVED** [review]

**Comment by JTPetter** [comment]
@Kucharssim I don't have write access to this repo, so my review does not count...

**Comment by Kucharssim** [comment]
@boutinb could you check whether this export is correct... Just need to export the two QML forms so that they can be used in another module.

**Comment by boutinb** [comment]
> @boutinb could you check whether this export is correct... Just need to export the two QML forms so that they can be used in another module.

The export seems correct to me. But I have never used a QML widget in a submodule from another submodule. I suppose you have tested it, and this works. That would also mean that jaspLearnStats will depend on jaspDistributions to be installed.

**Comment by Kucharssim** [comment]
> The export seems correct to me.

Ok, great, could you then approve it so that we can merge it?

**Comment by Kucharssim** [comment]
Or maybe @vandenman could approve it? :)

**Review by vandenman — APPROVED** [review]

**Pull request merged**
